name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: add go-gen
        run: |
          go get github.com/golang/protobuf/{proto,protoc-gen-go}
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: create work dir
        run: mkdir .grpc-out
      - name: test
        run: make protoc
